//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ArmazemModel
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ArmazemEntities : DbContext
    {
        public ArmazemEntities()
            : base("name=ArmazemEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Composicao> Composicao { get; set; }
        public virtual DbSet<Item_Requisicao> Item_Requisicao { get; set; }
        public virtual DbSet<Produto> Produto { get; set; }
        public virtual DbSet<Produto_Insumo> Produto_Insumo { get; set; }
        public virtual DbSet<Requisicao> Requisicao { get; set; }
    }
}
