//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ArmazemModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Item_Requisicao
    {
        public int Id { get; set; }
        public int Qtde { get; set; }
        public decimal Preco_Custo { get; set; }
        public int Requisicao_Codigo { get; set; }
        public int Produto_Codigo { get; set; }
    
        public virtual Produto Produto { get; set; }
        public virtual Requisicao Requisicao { get; set; }
    }
}
