//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ArmazemModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Requisicao
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Requisicao()
        {
            this.Item_Requisicao = new HashSet<Item_Requisicao>();
        }
    
        public int Codigo { get; set; }
        public System.DateTime Data_Abertura { get; set; }
        public string Responsavel { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Item_Requisicao> Item_Requisicao { get; set; }
    }
}
